[project]
name = "icaremc"
version = "0.1.0"
description = "FastAPI application"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "sqlalchemy",
    "alembic",
    "pydantic-settings",
    "asyncpg",
    "python-dotenv",
    "pyjwt>=2.13.0",
    "pwdlib[argon2]>=0.3.1",
    "httpx>=0.28.1",
    "email-validator>=2.3.0",
    "greenlet>=3.5.5",
]
